site_name: "AR Demo - Cloud Infra Docs"
site_url: "https://peak15-consul.github.io/Cloud-Infra-Management/"
repo_url: "https://github.com/peak15-consul/Cloud-Infra-Management"

docs_dir: Cloud-Infra-Docs/docs  # Ensure this points to the correct directory

theme:
  name: "material"
  palette:
    scheme: "slate"
    primary: "teal"
    accent: "blue"

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Cloud Infrastructure Management:
    - Overview: Cloud-Infrastructure-Management/overview.md
    - Architecture: Cloud-Infrastructure-Management/architecture-overview.md
    - Components and Services: Cloud-Infrastructure-Management/components-services.md
    - Supported Cloud Platforms: Cloud-Infrastructure-Management/supported-clouds.md
  - Deployment:
    - System Requirements: Deployment/system-requirements.md
    - Installation and Setup: Deployment/installation-and-setup.md