site_name: "AR Demo - Cloud Infra Docs"
site_url: "https://peak15-consul.github.io/Cloud-Infra-Management/"
repo_url: "https://github.com/peak15-consul/Cloud-Infra-Management"

docs_dir: Cloud-Infra-Docs/docs  # Ensure this points to the correct directory

theme:
  name: "material"
  palette:
    scheme: "slate"
    primary: "teal"
    accent: "blue"

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Cloud Infrastructure Management:
    - Overview: Cloud-Infrastructure-Management/overview.md
    - Architecture: Cloud-Infrastructure-Management/architecture-overview.md
    - Components and Services: Cloud-Infrastructure-Management/components-services.md
    - Supported Cloud Platforms: Cloud-Infrastructure-Management/supported-clouds.md
  - User-Management:
    - Overview: User-Management/user-management-overview.md
    - Authentication and Identity Management: User-Management/authentication-IAM.md
    - Access Control and Policy Management: User-Management/access-control-policy-management.md
    - Implementing User Management in Cloud Platforms: User-Management/cloud-platform-implementation.md
    - Troubleshooting User Management Issues: User-Management/troubleshooting.md
  - Deployment:
    - System Requirements: Deployment/system-requirements.md
    - Installation and Setup: Deployment/installation-and-setup.md
  - Resource Management:
    - Resource Management Overview: Resource-Management/resource-management.md
    - Adding & Managing Resources: Resource-Management/adding-managing-resources.md
    - Policy Management: Resource-Management/policy-management.md
    - Auto-Scaling: Resource-Management/auto-scaling.md
    - Resource Monitoring: Resource-Management/resource-monitoring.md
  - Costing and Budgeting:
    - Costing and Budgeting Overview: Costing-Budgeting/costing-budgeting-overview.md
    - Costing and Budgeting in Cloud Platforms: Costing-Budgeting/costing-budgeting-cloud-platforms.md
    - Costing and Budgeting Best Practices: Costing-Budgeting/costing-budgeting-best-practices.md