site_name: "AMOL REDIJ PROJECTS"

theme:
  name: "material"
  palette:
    scheme: "default"
    primary: "teal"
    accent: "red"

nav:
  - Home: index.md
  - Project Overview: project-overview.md
  - User Guide:
      - Getting Started: user-guide/getting-started.md
      - Features: user-guide/features.md
      - Integrations: user-guide/integrations.md
  - API Documentation:
      - Authentication: api-docs/authentication.md
      - Endpoints: api-docs/endpoints.md
      - Error Handling: api-docs/error-handling.md
  - Admin Guide:
      - Setup: admin-guide/setup.md
      - User Management: admin-guide/user-management.md
  - Troubleshooting:
      - Common Issues: troubleshooting/common-issues.md
  - FAQs:
      - FAQ: faqs/faq.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/youruser
