site_name: "AR Demo - Cloud Infra Docs"
site_url: "https://peak15-consul.github.io/Cloud-Infra-Management/"
repo_url: "https://github.com/peak15-consul/Cloud-Infra-Management"

theme:
  name: "material"
  palette:
    scheme: "default"
    primary: "teal"
    accent: "red"

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Cloud Infrastructure Management:
      - Overview: Cloud-Infrastructure-Management/overview.md
      - Architecture: Cloud-Infrastructure-Management/architecture-overview.md
      - Components and Services: Cloud-Infrastructure-Management/components-services.md
      - Supported Cloud Platforms: Cloud-Infrastructure-Management/supported-clouds.md
