name: Deploy MkDocs

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to the main branch
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install MkDocs and dependencies
        run: |
          pip install mkdocs mkdocs-material

      - name: Deploy MkDocs to GitHub Pages
        run: |
          cd Cloud-Infra-Docs  # Navigate to the directory where mkdocs.yml is located
          mkdocs gh-deploy --force