name: Deploy MkDocs

on:
  push:
    branches:
      - main  # Ensure this matches your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Build MkDocs site
        run: mkdocs build  # ✅ No need for extra config file paths

      - name: Disable Jekyll (avoid GitHub Pages errors)
        run: touch site/.nojekyll

      - name: Deploy MkDocs site  # ✅ Updated step with `disable_nojekyll: true`
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site  # Ensure this points to the built MkDocs site
          disable_nojekyll: true  # ✅ Explicitly disable Jekyll processing
