name: Deploy MkDocs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Debug directory structure before build
        run: ls -R

      - name: Build MkDocs site
        run: mkdocs build

      - name: Debug directory structure after build
        run: ls -R

      - name: Disable Jekyll
        run: |
          mkdir -p site
          touch site/.nojekyll

      - name: List contents of site directory
        run: ls -la site

      - name: Deploy MkDocs site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          disable_nojekyll: false  # ✅ Critical fix